version: "3"

services:
  frontend:
    build: ./frontend
    container_name: test-frontend
    image: muzamal/test-frontend:06
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: test-backend
    image: muzamal/test-backend:06
    volumes:
      - ./backend/index.js:/backend/index.js
    ports:
      - "5000:5000"
