version: "3"

services:
  frontend:
    build: ./frontend
    container_name: test-frontend
    image: 172.17.0.2:8085/test-frontend:01
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: test-backend
    image: 172.17.0.2:8085/test-backend:01
    volumes:
      - ./backend/index.js:/backend/index.js
    ports:
      - "5000:5000"
