apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mzml
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: muzamal/test-frontend:06
          ports:
            - containerPort: 5173
